### PR TITLE
Added TMDB

### PR DESCRIPTION
**Pull request by yevgenb**
Fixed TMDB.

### CODE REVIEW

**Comment by afedchin** [comment]
It's not usable, especially if two users will get info in the same time. You should use `X-RateLimit` header to inspect the status of limit, don't forget also that the limit is applied to all requests not only to search.

**Comment by yevgenb** [comment]
The TMDB limit is set to IP, not to API key. And yes, I know it's very rough rate limiter - I set 2.5 movie scans/sec that in the best case will bring us to 5 req/sec. If you add network + parsing overhead it will bring us to approx 3 req/sec. I did check X-RateLimit before setting this rate - it never reached limit in 2-3 month I tested it.

**Comment by afedchin** [comment]
I will take a look closer on this when I have spare time

**Comment by yevgenb** [comment]
Thank you! BTW - looks like they increased the rate limit to 4 req/sec

**Comment by yevgenb** [comment]
Самое забавное что теперь на винде это все страшно тормозит почему-то, а на моем рабочем маке все работает на ура.

**Comment by afedchin** [comment]
closed in favor of https://github.com/afedchin/xbmctorrent/commit/85e871b6ea29d5b734ae4ef0db73b3e7883931a2

**Pull request closed without merging**
